<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsc9bFj\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsc9bFj/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIsc9bFj.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIsc9bFj\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIsc9bFj\appAppKernelProdContainer([
    'container.build_hash' => 'Isc9bFj',
    'container.build_id' => '3c2d7c9b',
    'container.build_time' => 1728121856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsc9bFj');
