<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzDNkCXgknZyfoFlE3YdD'."\n".'52pV0h/ymB8DMzJLFYQHDzsB+XD7v6vESB6dVflIhcxKfTf9966Ctw+bz59egJDH'."\n".'NauqNpwpKtcTJD7z2867c/3ES6giFU9sE8cU8jqRAJxuAZBWf2sbtTYVFiGpikE6'."\n".'H4m21Fvw0nW1lMscGMBOBofFg+AWoZRhvblwRihd0Fe7zLMV24T/UJ0V+pt+IbXR'."\n".'9jjergH+rumTwURn2rSP3B2jJOHzFUfm3eIgWl+oSF7L/E99iByuFfgx3+jL2J/f'."\n".'3PAzrJh6W79kQhuMDUbEnhd9D1ey6pHap/r8h2UzYb/Yc92EBN14OSgNjsmKQIfb'."\n".'2QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
